### ISSUE TITLE
Incorrect TTWROR in Yearly returns in heat map widget for benchmarks

### ISSUE THREAD

**Issue by thomasfaingnaert** [portfolio-performance/mobile-app#11]
In the mobile app, the "Yearly returns in a heat map" widget displays the incorrect TTWROR for benchmarks: it displays the non-benchmark TTWROR instead.

Compare desktop:
![image](https://github.com/portfolio-performance/mobile-app/assets/10748726/d3c7a58d-52a4-4166-ace8-b9b05fe9d7fe)

And mobile:
![image](https://github.com/portfolio-performance/mobile-app/assets/10748726/1dff869a-d5cd-487c-92a4-cb047326cc38)

Simple portfolio file used:
[mwe.zip](https://github.com/portfolio-performance/mobile-app/files/14541692/mwe.zip)

Great work on the mobile app, by the way! This is something I've been missing.

By the way, I noticed that the mobile app is closed source for now. Do you have any plans to open source it in the long term?

**Comment by buchen** [comment]
> By the way, I noticed that the mobile app is closed source for now. Do you have any plans to open source it in the long term?

I have two challenges with open sourcing:
* first, it would be super easy to publish "clones" into the app store.
* second, I have to provide proof of copyright to the code.

Obviously, the second part should prevent the first part, but I am not sure if the review processes by the store are that good. And, a contributor license agreement (CLA) could go some way to address the second part. For the time being, I did not focus on solving this.


Will check the calculation of the benchmark.

**Comment by buchen** [comment]
Will publish a hot fix release for this.

<img width="1036" alt="Bildschirmfoto 2024-03-11 um 08 47 31" src="https://github.com/portfolio-performance/mobile-app/assets/587976/79ad90ae-c046-4e29-b357-fe49ca4430bc">

**Comment by buchen** [comment]
@thomasfaingnaert if you [drop me an email](mailto:support@portfolio-performance.app) and your device type (iOS, Android), I can provide you with a test(flight) version

**Comment by buchen** [comment]
published with 1.0.5
