### ISSUE TITLE
Historical Quotes with JSON Provider: Factor for quotes ignored?

### ISSUE THREAD

**Issue by hmfetzer** [portfolio-performance/mobile-app#12]
**First: congratulations for the android app. It looks and feels great!**

To manage bonds with a percent quote, I set the field "Factor (for quotes)" in the "Edit Assets /  Historical Quotes" window to "0.01". 

This works fine when also setting the number of shares to the principal value of the bond - but only in the desktop version! In the android app the shown values of the bonds investments are one hundred times to high. Looks like the multiplication of the quote with the factor is not made?

E.g Feed URL: https://api.onvista.de/api/v1/instruments/BOND/2/eod_history?idNotation={TICKER}&range=M1&startDate={TODAY:yyyy-MM-dd:-P1M}&withEarnings=false

with TICKER=380098416:

https://api.onvista.de/api/v1/instruments/BOND/2/eod_history?idNotation=380098416&range=M1&startDate=2024-03-07&withEarnings=false

![grafik](https://github.com/portfolio-performance/mobile-app/assets/3121502/e8bbe7e4-b15c-4c5a-9695-74d902896170)

Problem occurs in version 1.0.4

**Comment by buchen** [comment]
Indeed. I missed that when implementing it on the mobile app.

**Comment by buchen** [comment]
published with 1.0.5
