### ISSUE TITLE
Android App not allowed to open .xml by OS File Picker

### ISSUE THREAD

**Issue by ddonchev** [portfolio-performance/mobile-app#13]
Phone: Samsung Galaxy S21 Ultra 5G; Android 14; Samsung One UI 6.0; Samsung My Files v. 15.0.03.25 (latest)

Steps to reproduce:
1. Open the app and press the 'Open portfolio' button
2. Try to open any .xml file via the file picker (in this case Samsung's My Files)

Symptom: Most file types are dimmed and not select-able to open (except a few with extensions .gpx .cfg, .kbd)

Reproducible regardless of the file name or location ('Internal Storage' or 'Nextcloud' syncing it from a remote server)

**Workaround**: 
1. Open your *.xml file with Portfolio Performance desktop app; 
2. File -> Save as -> **binary**
3. Save the file with the *.portfolio extension. 
4. Find and open the *.portfolio file in the android app.

**Comment by buchen** [comment]
Hey @ddonchev,

unfortunately, I have not implemented support for the XML format in the mobile application. Already on the desktop, the XML parsing is inefficient and slow. And on the mobile device even less so. Obviously, I have to make that fact more clearer in the app and on the desktop. At the moment, I do not plan to implement support for XML.

The binary is storing the same data. It is using protobuf (which has a nice Java and Dart implementation and therefore works good on the desktop and mobile).

I am aware of the disadvantage: one cannot edit the XML anymore directly and then just open the file.

Andreas.

P.S.: looking forward to talking to you soon. April.
