### ISSUE TITLE
Dividendendarstellung im Reiter Vermögen: Sigma als  Summensymbol(U+2211)

### ISSUE THREAD

**Issue by PerformerTh** [portfolio-performance/mobile-app#26]
Version 1.1.0+57
Nur Optikverbesserung - keine funktionale Verbesserung

Im Reiter Vermögen ist die Layout-Option "Zeitraum" wählbar. Mit dieser wird eine kompakte Darstellung der Wertpapiere nebst Grafik ermöglicht - super.
Dividenden werden derzeit wie folgt dargestellt:

![Screenshot_20240322_195008_Portfolio Performance](https://github.com/portfolio-performance/mobile-app/assets/161111865/2f9eae6b-e16c-40c0-971e-b740485fbc5e)

"Schöner" als das C (für Cash?) wäre das Sigma ∑ als Darstellung der Dividendensumme
Gruß Thomas

**Comment by buchen** [comment]
> "Schöner" als das C (für Cash?) wäre das Sigma ∑ als Darstellung der Dividendensumme

Haha, das ist ein Rendering Problem. Der Font kann auf Android das Sigma nicht.

**Comment by PerformerTh** [comment]
In Version 1.2.0+61 gelöst
