### ISSUE TITLE
Feature wish: Showing and hiding individual curves in a diagram

### ISSUE THREAD

**Issue by ThomasRudolphJ** [portfolio-performance/mobile-app#35]
It would be beneficial to have the possibility to show and hide individual curves in a diagram and perform an auto scaling based on the remaining charts. If there are several charts in one diagram and one has much higher values than the others, their curve progression is nearly invisible.
Alternatively a manual scaling should be allowed (y-axix min/max value, ...).

**Comment by buchen** [comment]
With the next version, there is the option to temporarily hide data series.

![Simulator Screenshot - iPhone 15 Pro - 2024-08-31 at 07 38 26](https://github.com/user-attachments/assets/fbbe2016-c14c-48f8-bd1c-3ca95bfd69c9)
